#!/bin/bash
#SBATCH -J postRun
#SBATCH -p wzhcnormal
#SBATCH -N 1
#SBATCH --ntasks-per-node=64
module purge
module load compiler/devtoolset/7.3.1
module load mpi/openmpi/4.1.1/gcc-7.3.1
export UCX_NET_DEVICES=mlx5_0:1
export UCX_IB_PCI_BW=mlx5_0:100Gbs

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

nProc=$(getNumberOfProcessors)

# Set solver name

solver="mpirun --oversubscribe -np $nProc postProcess -func Q  -parallel"

# Run the solver
runApplication $solver 
runApplication reconstructPar
runApplication foamToVTK
mv log.mpirun log.Q
