#!/bin/bash
#SBATCH -J preRun
#SBATCH -p wzhcnormal
#SBATCH -N 1
#SBATCH --ntasks-per-node=60
module purge
module load compiler/devtoolset/7.3.1
module load mpi/openmpi/4.1.1/gcc-7.3.1
export UCX_NET_DEVICES=mlx5_0:1
export UCX_IB_PCI_BW=mlx5_0:100Gbs
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Use the correct decomposeParDict
rm ./system/decomposeParDict
cp ./system/decomposeParDict_pre ./system/decomposeParDict

# Get number of processors from decomposePar dict
nProc=$(getNumberOfProcessors)


#Run blockMesh
runApplication blockMesh

#Decompose mesh for snappyHex
runApplication decomposePar

#Run snappyMesh
mesh_application="mpirun --oversubscribe -np $nProc snappyHexMesh -overwrite -parallel"
runApplication $mesh_application
mv log.mpirun log.snappyHexMesh
#### runApplication snappyHexMesh -overwrite

#Reconstruct mesh
#This is needed, see https://www.cfd-online.com/Forums/openfoam-meshing/239688-cannot-find-patchfield-entry.html
runApplication reconstructParMesh -mergeTol 1e-06 -latestTime -constant

#Remove parallel files
rm -rf processor*
rm -rf log.decomposePar

# Run topoSet
runApplication topoSet

